-- 코드를 입력하세요
SELECT pd.PRODUCT_CODE AS PRODUCT_CODE, SUM(pd.PRICE * os.SALES_AMOUNT) AS SALES
FROM PRODUCT AS pd JOIN OFFLINE_SALE AS os ON pd.PRODUCT_ID = os.PRODUCT_ID
GROUP BY pd.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE